# Generated by Django 4.1.7 on 2023-04-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'blog_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TBlog',
            fields=[
                ('blog_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_content', models.TextField()),
                ('blog_status', models.IntegerField()),
                ('create_time', models.DateTimeField()),
                ('update_time', models.DateTimeField()),
                ('cover_image', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 't_blog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TComment',
            fields=[
                ('comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment_content', models.CharField(max_length=500)),
                ('createtime', models.DateTimeField()),
                ('replyid', models.IntegerField()),
            ],
            options={
                'db_table': 't_comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TTag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 't_tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TTagBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 't_tag_blog',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
    ]
